In [25]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
import numpy as np

iris = load_iris()
data = pd.DataFrame(iris.data, columns=iris.feature_names)

X = data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=5)

model1 = LogisticRegression()
model1.fit(X_train, y_train)
y_pred = model1.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(f1_score(y_test, y_pred, average='macro'))
print(confusion_matrix(y_test, y_pred))
print()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=0)

model2 = LogisticRegression()
model2.fit(X_train, y_train)
y_pred = model2.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(f1_score(y_test, y_pred, average='macro'))
print(confusion_matrix(y_test, y_pred))
print()


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=8)

model3 = LogisticRegression()
model3.fit(X_train, y_train)
y_pred = model3.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(f1_score(y_test, y_pred, average='macro'))
print(confusion_matrix(y_test, y_pred))
print()


0.9130434782608695
0.9074074074074074
[[8 0 0]
 [0 5 1]
 [0 1 8]]

1.0
1.0
[[ 7  0  0]
 [ 0 11  0]
 [ 0  0  5]]

0.8695652173913043
0.8745098039215686
[[7 0 0]
 [0 6 1]
 [0 2 7]]



In [29]:
from sklearn.model_selection import KFold,StratifiedKFold,LeaveOneOut, cross_val_score

X_np = X.values

kf = KFold(n_splits=3, shuffle=True, random_state=15)
for i, (train_index, test_index) in enumerate(kf.split(y)):
    print(f'Fold {i+1}: Длина train: {len(train_index)}, test: {len(test_index)}')
    print(f'Train: {train_index}, Test: {test_index}')
    print()

metrics_accuracy = []
metrics_f1 = []
model = LogisticRegression(max_iter=1000)
for i, (train_index, test_index) in enumerate(kf.split(y)):
    X_train, X_test = X_np[train_index], X_np[test_index]
    y_train, y_test = y[train_index], y[test_index]
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    metrics_accuracy.append(accuracy_score(y_test, y_pred))
    metrics_f1.append(f1_score(y_test, y_pred, average='macro'))

print(f'Значения метрик accuracy: {metrics_accuracy} \n Значение метрик f1: {metrics_f1}')

print(f'Среднее по кросс-валидации: {np.array(metrics_accuracy).mean()}')
print(f'Среднее по кросс-валидации: {np.array(metrics_f1).mean()}')



Fold 1: Длина train: 100, test: 50
Train: [  1   2   3   4   7  10  14  15  16  17  18  19  22  23  24  26  28  29
  32  33  34  35  37  38  39  40  41  42  43  44  45  46  49  50  51  52
  53  54  56  60  62  63  64  65  66  68  69  70  73  75  76  77  79  80
  81  82  83  85  87  88  91  92  93  94  96  99 101 102 104 105 106 107
 108 110 111 113 114 117 118 119 120 121 123 125 128 131 132 133 134 135
 136 137 139 140 141 142 144 145 146 147], Test: [  0   5   6   8   9  11  12  13  20  21  25  27  30  31  36  47  48  55
  57  58  59  61  67  71  72  74  78  84  86  89  90  95  97  98 100 103
 109 112 115 116 122 124 126 127 129 130 138 143 148 149]

Fold 2: Длина train: 100, test: 50
Train: [  0   1   4   5   6   7   8   9  10  11  12  13  15  17  19  20  21  22
  23  24  25  26  27  28  30  31  34  36  37  39  40  41  42  44  47  48
  50  53  55  56  57  58  59  60  61  62  63  65  66  67  70  71  72  74
  75  78  79  84  85  86  89  90  95  96  97  98  99 100 101 102 103 104
 105 

In [32]:
cv_result = cross_val_score(model, X_np, y, cv=kf, scoring='accuracy', n_jobs=-1)

print('Кросс-валидация: ', cv_result)
print('Среднее по кросс-валидация: ', cv_result.mean())
print('Дисперсия по кросс-валидации: ', cv_result.std())
print()

loo = LeaveOneOut()

for i, (train_index, test_index) in enumerate(loo.split(y)):
    print(f'Fold {i+1}: Длина train: {len(train_index)}, test: {len(test_index)}')
    print(f'Train: {train_index}, Test: {test_index}')
    print()

cv_result = cross_val_score(model, X_np, y, cv=loo, scoring='f1_macro', n_jobs=-1)

print('Кросс-валидация: ', cv_result)
print('Среднее по кросс-валидация: ', cv_result.mean())
print('Дисперсия по кросс-валидации: ', cv_result.std())
print()

Кросс-валидация:  [1.   0.94 0.94]
Среднее по кросс-валидация:  0.96
Дисперсия по кросс-валидации:  0.028284271247461926

Fold 1: Длина train: 149, test: 1
Train: [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149], Test: [0]

Fold 2: Длина train: 149, test: 1
Train: [  0   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44